#! /bin/sh

echo "SOCKD_PORT: $SOCKD_PORT"
echo "SOCKD_USERNAME: $SOCKD_USERNAME"
echo "SOCKD_PASSWORD: $SOCKD_PASSWORD"


( [ ! -z "$SOCKD_USERNAME" ] && [ ! -z "$SOCKD_PASSWORD" ] ) && \
    echo "Add new user " && \
    sh /home/script/pam add $SOCKD_USERNAME $SOCKD_PASSWORD

CONF_FILE="/home/danted/conf/sockd.conf"

port_change(){
    echo "Change port to $1"
    sed -i "s/2020/$1/g" $CONF_FILE
}

( [ ! -z "$SOCKD_PORT" ] ) && \
    echo "Add new port" && \
    port_change $SOCKD_PORT

exit 0